# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  test-executor:
    docker:
      - image: circleci/node:9.8-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"

    working_directory: ~/glui
  prod-executor:
    docker:
      - image: circleci/node:9.8

    working_directory: ~/glui

jobs:
  build:
    executor: test-executor
    steps:
      - checkout

      - attach_workspace:
          at: ~/glui

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: 
          name: Run unit tests
          command: npm run test glui-glui

      - persist_to_workspace:
          root: .
          paths:
            - .
  
  # Build production dist
  build-prod:
    executor: prod-executor
    steps:
      - attach_workspace:
          at: ~/glui
      - run:
          name: Build production distribution for deploy
          command: npm run build --prod
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    executor: prod-executor
    steps:
      - attach_workspace:
          at: ~/glui
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2.1
  test-build-deploy:
    jobs:
      - build:
          filters:
            branches:
              - development
              - master
              - production
      - build-prod:
          requires:
            - build
          filters:
            branches:
              only: 
                - production
      - deploy:
          requires:
            - build-prod
          filters:
            branches:
              only: 
                - production